[project]
name = "ksu-cis560-project-app"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "flask>=3.1.2",
    "pyodbc>=5.2.0",
]
