[project]
name = "ksu-cis560-project-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.2",
    "pyodbc>=5.2.0",
]
